### ISSUE TITLE
复现小问题

### ISSUE THREAD

**Issue by lsy00fsq** [fuen1590/PhmDeepLearningProjects#1]
请问我运行experiments.py文件后有model result，但是没有utils文件里面的评估指标（RMSE,MAE等）

**Comment by fuen1590** [comment]
您好@lsy00fsq 
我们在utils中提供的`compute_metrics(path)`方法并未直接集成到整个训练流程中，您可以通过下述步骤计算最终的性能指标（RMSE,MAE等）：
1. 查看model_result文件夹中是否有对应的训练结果文件夹，以及其是否包含测试集下的输出文件`model_test_output_part1.npy`和`model_test_labels_part1.npy`，包含这两者则说明您的训练过程没有任何问题
2. 手动调用`compute_metrics(path)`，其中path参数指向包含`model_test_output_part1.npy`和`model_test_labels_part1.npy`的上层文件夹的绝对路径即可直接计算RMSE、MAE等
3. 您还可以自己实现指标的计算流程，所用到的数据均包含在`model_test_output_part1.npy`和`model_test_labels_part1.npy`中，二者的形状完全一致，您可以快速处理它们

**Comment by lsy00fsq** [comment]
好的明白，谢谢你的解答！！！

**Comment by lsy00fsq** [comment]
好的，谢谢您的解答

**Comment by fuen1590** [comment]
不客气，感谢您对本项目的关注，如有任何关于本项目的其他问题欢迎开放新的Issue讨论
