### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by xiaohe-jiayou** [fuen1590/PhmDeepLearningProjects#3]
import dataset.xjtu as xjtu中的xjtu是什么文件，在dataset文件夹下没有这个文件，程序跑不通，显示“ModuleNotFoundError: No module named 'dataset.xjtu'”

**Comment by fuen1590** [comment]
这是我们处理仓库代码时的遗留问题，直接删除即可，感谢您的提醒。我们已经上传了修改后的experiment，您可以自行删除或重新fork. @xiaohe-jiayou

**Comment by xiaohe-jiayou** [comment]
好的，谢谢您
